name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (if needed)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          
          # For testing, allow any incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          # (Optional) Restart the Remote Desktop service to ensure changes take effect
          Restart-Service -Name TermService -Force

      - name: Create RDP User with Secure but Simple Password
        run: |
          # Generate password with required complexity but exclude problematic special characters
          # Requirements: 8+ chars, uppercase, lowercase, number, and safe special chars
          $upperChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
          $lowerChars = "abcdefghijklmnopqrstuvwxyz"
          $numberChars = "0123456789"
          # Exclude problematic chars like: " ' ` | < > & % \ / : ; 
          $safeSpecialChars = "!@#$*+=?-_"
          
          # Build password with guaranteed complexity
          $password = ""
          $password += ($upperChars.ToCharArray() | Get-Random -Count 3) -join ""
          $password += ($lowerChars.ToCharArray() | Get-Random -Count 3) -join ""
          $password += ($numberChars.ToCharArray() | Get-Random -Count 2) -join ""
          $password += ($safeSpecialChars.ToCharArray() | Get-Random -Count 2) -join ""
          
          # Shuffle the password characters
          $passwordArray = $password.ToCharArray()
          $shuffledPassword = ($passwordArray | Sort-Object { Get-Random }) -join ""
          
          $securePass = ConvertTo-SecureString $shuffledPassword -AsPlainText -Force
          
          # Create user
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires -PasswordNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          
          echo "RDP_CREDS=User: RDP | Password: $shuffledPassword" >> $env:GITHUB_ENV
          
          if (-not (Get-LocalUser -Name "RDP")) {
              Write-Error "User creation failed"
              exit 1
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key and set a unique hostname
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          # Wait for Tailscale to assign an IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
      
      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          
          # Test connectivity using Test-NetConnection against the Tailscale IP on port 3389
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Save RDP Info
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: RDP"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"
          
          # Create JSON entry for this server
          $serverData = @{
              "id" = (Get-Date).ToString("yyyyMMddHHmmss")
              "ip" = $env:TAILSCALE_IP
              "username" = "RDP"
              "password" = $env:RDP_CREDS
              "created" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
          }
          
          # Save to file
          $serverData | ConvertTo-Json | Out-File "server-info.json" -Encoding UTF8
          Write-Host "Server info saved to server-info.json"

      - name: Upload Server Info
        uses: actions/upload-artifact@v3
        with:
          name: server-info-${{ github.run_id }}
          path: server-info.json
          
      - name: Maintain Connection
        run: |
          # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
